Redon
aray-course/tribute-tmnt pull request #1
Opened 2024-10-25 22:15 UTC by RedonTahiri

Pull request to merge Redon to main branch

2024-10-26 07:01 UTC, ylberprapashtica requested changes

2024-10-26 07:01 UTC, ylberprapashtica commented on public/base.css
Pse e ki prek base.css?

2024-10-26 07:01 UTC, ylberprapashtica commented on public/redon.css
> +.gejimages {
Zgjedhe ni gjuhe per ja shqip ja anglisht me i emertu senet.
Edhe zakonisht i lajm emrat e classave "https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/".
Tl;DR: Ndaj fjalt me viza p.sh: redon-tahiri, gay-images.

2024-10-26 07:01 UTC, ylberprapashtica commented on public/redon.css
> +.gejimages img {
Pse i ki jep tagut img, background image? A po shihet ne faqe?

2024-10-26 07:01 UTC, ylberprapashtica commented on public/redon.html
> +        <img src="img/gay1.jpg" width="400" height="400">
Stiliziming e elemente e bojme ne css. Heki "width="400" height="400".

2024-10-26 07:01 UTC, ylberprapashtica commented on public/redon.html
> +            <li><a href="#" class="fa fa-facebook">Facebook</a></li>
Cka eshte kjo fa fa-facebbok edhe fa fa-instagram?

2024-10-26 07:02 UTC, ylberprapashtica commented on public/base.css
Ti bona do ndryshime qe mos me pak konflikt me main. Edhe tash tdel linku per me muj me pa une qysh doket webfaqj ne browser.

2024-10-26 12:54 UTC, RedonTahiri commented on public/redon.html
> +            <li><a href="#" class="fa fa-facebook">Facebook</a></li>
Awesome Font osht qe ja kom shtu per me i bo ikonat e facebook edhe instagram

2024-10-26 12:55 UTC, RedonTahiri commented on public/redon.css
> +.gejimages img {
.gejimages permban edhe content tjeter perveq images kshtu qe mu ka duft mer target veq img tag

2024-10-27 18:40 UTC, ylberprapashtica commented on public/redon.css
> +@keyframes fadeInAnimation {
Interesant, na spjegon t'hanen cka ki bo qitu :)

2024-10-27 18:41 UTC, ylberprapashtica approved these changes
Spo di pse i ki bo merge senet e endritit edhe endit?

2024-10-27 20:20 UTC, merged